# This file was generated by GoReleaser. DO NOT EDIT.
cask "cclint" do
  name "cclint"
  desc "A linter for Claude Code configurations"
  homepage "https://github.com/pthm/cclint"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cclint"

  on_macos do
    on_intel do
      url "https://github.com/pthm/cclint/releases/download/v#{version}/cclint_#{version}_darwin_amd64.tar.gz"
      sha256 "eb43cacb1c1e4dc2f0e5a4dd0ded02962e1494a8f728ea4ce0f1383360051ca9"
    end
    on_arm do
      url "https://github.com/pthm/cclint/releases/download/v#{version}/cclint_#{version}_darwin_arm64.tar.gz"
      sha256 "2bf40c0f7498ca393d12032fc345b6ba710e1058fc283eed9225b4dcec63cba4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pthm/cclint/releases/download/v#{version}/cclint_#{version}_linux_amd64.tar.gz"
      sha256 "4e2753d5ae5321834271df66caa565e05fc9f3fcfe9eaea6b788cbb25fc77bcf"
    end
    on_arm do
      url "https://github.com/pthm/cclint/releases/download/v#{version}/cclint_#{version}_linux_arm64.tar.gz"
      sha256 "9fbb012ed8ce988110e0b25cca85158640b9c715234116efb74b6d4793841721"
    end
  end

  # No zap stanza required
end
