# This file was generated by GoReleaser. DO NOT EDIT.
cask "cclint" do
  name "cclint"
  desc "A linter for Claude Code configurations"
  homepage "https://github.com/pthm/cclint"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cclint"

  on_macos do
    on_intel do
      url "https://github.com/pthm/cclint/releases/download/v#{version}/cclint_#{version}_darwin_amd64.tar.gz"
      sha256 "5aa95c255f3e3c10fd4c01caff36f7c6d1e3daf9c1c23c52543e8283a2e42c09"
    end
    on_arm do
      url "https://github.com/pthm/cclint/releases/download/v#{version}/cclint_#{version}_darwin_arm64.tar.gz"
      sha256 "729e0209c055cea998d632650b0608ef55ca2c530f1f483fe50a5e280c515cc4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pthm/cclint/releases/download/v#{version}/cclint_#{version}_linux_amd64.tar.gz"
      sha256 "9eb2a1131371f3c6eca3337e96f3c561de905dbad8b48284e152022aa7217fa9"
    end
    on_arm do
      url "https://github.com/pthm/cclint/releases/download/v#{version}/cclint_#{version}_linux_arm64.tar.gz"
      sha256 "35df1002fc00a48f8047fbdb7f8f340bff340ad9d683ae544ab970f590d501a0"
    end
  end

  # No zap stanza required
end
