# This file was generated by GoReleaser. DO NOT EDIT.
cask "melange" do
  version "0.8.2"

  on_macos do
    on_intel do
      sha256 "8337cffd283ef310f2e344e55ac3e8889b4caaa75f80f9d17bd800aa19413153"
      url "https://github.com/pthm/melange/releases/download/v#{version}/melange_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0aab2092115baf9748bcc453646c5b1efeb3362b127c0d413710db22137b7c1c"
      url "https://github.com/pthm/melange/releases/download/v#{version}/melange_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "796415337227e29a1e9614d471aa0dd86866ec177b3d6ed33bfa81b4a128c96a"
      url "https://github.com/pthm/melange/releases/download/v#{version}/melange_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c8df41f8513034005602a43cdb0b473c51d60768f9a76082dafba475a61b2ace"
      url "https://github.com/pthm/melange/releases/download/v#{version}/melange_#{version}_linux_arm64.tar.gz"
    end
  end

  name "melange"
  desc "PostgreSQL Fine-Grained Authorization - OpenFGA to SQL compiler"
  homepage "https://github.com/pthm/melange"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "melange"

  # No zap stanza required

end
