# This file was generated by GoReleaser. DO NOT EDIT.
cask "melange" do
  version "0.8.3"

  on_macos do
    on_intel do
      sha256 "f9be225eeaafbca08f60d54a81a9b3fe4fd3676f7c5f2beca9665bc5c3cb2671"
      url "https://github.com/pthm/melange/releases/download/v#{version}/melange_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5aabbdb737597fa54910c18c86ad57ac32d240778334bbc9a8f8eee7a28497d7"
      url "https://github.com/pthm/melange/releases/download/v#{version}/melange_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "534cf5358c59ed4dc2784b2189e71f137785d2939f5fb4262b96866d3702bb49"
      url "https://github.com/pthm/melange/releases/download/v#{version}/melange_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2cde9f63f20188e456a26ac4b0c340d7a514e40826b70ef8b379c017b0673d90"
      url "https://github.com/pthm/melange/releases/download/v#{version}/melange_#{version}_linux_arm64.tar.gz"
    end
  end

  name "melange"
  desc "PostgreSQL Fine-Grained Authorization - OpenFGA to SQL compiler"
  homepage "https://github.com/pthm/melange"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "melange"

  # No zap stanza required

end
