# This file was generated by GoReleaser. DO NOT EDIT.
cask "melange" do
  version "0.8.5"

  on_macos do
    on_intel do
      sha256 "9756ced1ae742cb02c4c0bfc60827777036cb36c2d26955132b2cd18bd899b35"
      url "https://github.com/pthm/melange/releases/download/v#{version}/melange_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "59c233736ee3fe60c29ab92beff9802df09f282650ef7b489b51bd0bc0644c98"
      url "https://github.com/pthm/melange/releases/download/v#{version}/melange_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6c4569544777bb5414532af8298098517a74e0afe39cef4a46f60c1cf8c9b051"
      url "https://github.com/pthm/melange/releases/download/v#{version}/melange_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "06b29b758eab9c7406635e57defb7a37924788295f6aa470ca1e77ac14355a7d"
      url "https://github.com/pthm/melange/releases/download/v#{version}/melange_#{version}_linux_arm64.tar.gz"
    end
  end

  name "melange"
  desc "PostgreSQL Fine-Grained Authorization - OpenFGA to SQL compiler"
  homepage "https://github.com/pthm/melange"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "melange"

  # No zap stanza required

end
